# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_key', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(choices=[('SHOWER', 'Shower'), ('BRUSH TEETH', 'Brush Teeth'), ('DO HOMEWORK', 'Do Homework'), ('BRUSH HAIR', 'Brush Hair'), ('GET DRESSED', 'Get Dressed')], default='SHOWER', max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_key', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateTimeField(verbose_name='Date Joined')),
                ('birthdate', models.DateTimeField(verbose_name='Birthdate')),
                ('average_spoons', models.PositiveIntegerField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
