# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_key', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=60)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
