# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoons', '0003_auto_20171128_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], default='UNKNOWN', max_length=20),
        ),
    ]
