# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoons', '0005_auto_20171129_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoonuser',
            name='birthdate',
            field=models.DateField(verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='spoonuser',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spoonuser',
            name='user_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='Unknown', max_length=20),
        ),
    ]
