# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spoons', '0007_auto_20171129_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoonProfile',
            fields=[
                ('user_key', models.AutoField(primary_key=True, serialize=False)),
                ('user_gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='Unknown', max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('average_spoons', models.PositiveIntegerField()),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='spoonuser',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='SpoonUser',
        ),
    ]
