# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoons', '0009_auto_20171130_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spoonprofile',
            old_name='profile_name',
            new_name='username',
        ),
    ]
