# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoons', '0010_auto_20171130_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoonprofile',
            name='count_style',
            field=models.CharField(choices=[('Up', 'Count Up'), ('Down', 'Count Down')], default='up', max_length=4),
        ),
        migrations.AlterField(
            model_name='spoonprofile',
            name='average_spoons',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
